name: "Add Assignee when is labeled with 'A: In progress'"

on:
  issues:
    types: [labeled]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelName = context.payload.label.name;
            const senderName = context.payload.sender.login;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issueNumber = context.issue.number;
            const assignees = context.payload.issue.assignees.map(a => a.login);

            if (labelName === 'A: In progress' && !assignees.inclues(senderName)) {
              console.log(`Adding ${senderName} to the #${issueNumber} assignees`);
              await github.issues.addAssignees({
                owner,
                repo,
                issue_number: issueNumber,
                assignees: [ senderName ],
              });
            }
