name: "Add Assignee when is labeled with 'A: In progress'"

on:
  issues:
    types: [labeled]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('CONTEXT');
            console.log(context);
            console.log('ISSUE');
            console.log(context.payload.issue);
            console.log('ASSIGNEES');
            console.log(JSON.stringify(context.payload.issue.assignees, 0, 4))

            const labelName = context.payload.label.name;
            const senderName = context.payload.sender.login;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issueNumber = context.issue.number;

            if (labelName === 'A: In progress') {
              github.issues.addAssignees({
                owner,
                repo,
                issue_number: issueNumber,
                assignees: [ senderName ],
              });
            }
