name: 'Close stale issues created via github'
on:
  schedule:
    - cron: '00 10 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has been open 4 days with no activity. Please note, that our resources are limited and we can not always take the time to respond to all requests. The issue will be closed if no further activity occurs. However, if you want to help solve the issue and you have some knowledge about creating rules, you are welcome to create a pull request following [these instructions](https://github.com/AdguardTeam/AdguardFilters/blob/master/CONTRIBUTING.md). Thank you for your contributions.'
          stale-issue-label: 'Stale'
          exempt-issue-labels: 'A: By design,A: In progress,A: Problematic'
          only-issue-labels: 'Unsorted'
          exempt-all-issue-assignees: true
          days-before-issue-stale: 4
          days-before-issue-close: 3
          remove-issue-stale-when-updated: true
